## ===================================================================
## GitMyNotes - LICENSE AND CREDITS
## This app/collection of scripts at https://github.com/mariochampion/gitmynotes
## released under the GNU General Public License v3.0
##
## 
## GitMyNotes scripts crafted and copyright 2024 by mario champion (mariochampion.com) 
##
## please open issues and pull requests and comments
## thanks and always remember: this robot loves you. 
## boop boop!!!
## ===================================================================


#### Important
##
##   Any ADDITIONAL 'DEFAULT_*'configs added to this file must be also added to gitmynotes.py
##   in the 'USER CONFIGS' section atop that file
##
####


#### User Configs
##
##   REQUIRED TO CHANGE the '<ChangeMe>' github username. 
##   You can create a repo named 'gitmynotes' for max convenience.
##   Make sure your GitHub access/authentication is setup for this repo.  
'DEFAULT_GITHUB_URL': 'https://github.com/<ChangeMe>/gitmynotes'


##   REQUIRED: LEAVE AS-IS or CHANGE--
'DEFAULT_NOTES_FOLDER': 'Notes' # This is the default folder (found on every macOS Notes app) to be processed if --folder not set.
'DEFAULT_EXPORT_PATH': '~/Documents/gitmynotes'
'DEFAULT_PROCESSED_FOLDER_ENDING': '__GitMyNotes' # ex: if folder is "plans", this will create temp folder "plans__GitMyNotes"
'DEFAULT_NOTES_WRAPPERDIR': 'macosnotes' # this is the dir in Github in which notes folders will be created
'DEFAULT_RESTORE_NOTES': 'empty' # options are "empty, always, never"
'DEFAULT_BATCH_SIZE': 10 # notecount / batchsize = loopcount. 'notecount' is either explicit as 'maxnotes' or returned from get_foldernotecount(folder) if maxnotes not set.
'DEFAULT_LOOPCOUNT_BEFORE_CONFIRM': 5 # loopcount X batchsize = notecount before you must confirm intention to process in one run. This can be over-ridden for use in full automation by adding '--force' to your command.
#'PRINT_LEVEL': "RESULTS"  # Can be "NONE", "RESULTS", "DEBUG", or "ALL"

# I wouldnt change these, personally.
'DEFAULT_NEWLINE_DELIMITER': '|||' # this is for internal use when creating local audit file, like "plans.csv"
'DEFAULT_AUDIT_FILE_ENDING': '.csv' # so that .csv audit files are named accurately 
'DEFAULT_CURRENTNOTE_FILE': 'currentnote.txt'



#### GitMyNotes Usage Data
##
##   This data is not transmitted anywhere. 
##   It is used to enable first-time help, when DEFAULT_GITHUB_URL is 0, for example
##   And to help show the benefit you have received using GitMyNotes

'USAGE_GITMYNOTES_TOTAL': 0
'USAGE_FOLDERS_PROCESSED':
- placeholder
'USAGE_NOTES_PROCESSED': 0


