## ===================================================================
## GitMyNotes - LICENSE AND CREDITS
## This app/collection of scripts at https://github.com/mariochampion/gitmynotes
## released under the GNU General Public License v3.0
##
## 
## GitMyNotes scripts crafted and copyright 2024 by mario champion (mariochampion.com) 
##
## please open issues and pull requests and comments
## thanks and always remember: this robot loves you. 
## boop boop!!!
## ===================================================================


####
##  IMPORTANT: Any ADDITIONAL 'DEFAULT_*'configs added to this file must be also added to gitmynotes.py
##  in the 'USER CONFIGS' section atop that file


#### user configs
##   REQUIRED TO CHANGE
'DEFAULT_GITHUB_URL': 'https://github.com/<changeme>/gitmynotes'


##   REQUIRED: LEAVE AS-IS or CHANGE--
'DEFAULT_NOTES_FOLDER': 'Notes'
'DEFAULT_EXPORT_PATH': '~/Documents/gitmynotes'
'DEFAULT_NOTES_WRAPPERDIR': 'macosnotes'
'DEFAULT_PROCESSED_FOLDER_ENDING': '__GitMyNotes'
'DEFAULT_CSV_NAME': 'gitmynotes.csv'
'DEFAULT_AUDIT_FILE_ENDING': '.csv'

'DEFAULT_NOTES_FOLDER_FORCE':
'DEFAULT_NOTECOUNT_BEFORE_CONFIRM': 5
'DEFAULT_BATCH_SIZE': '10'
'DEFAULT_NEWLINE_DELIMITER': '|||'
'DEFAULT_RESTORE_NOTES': 'empty'



#### GitMyNotes Usage data
##   This data is not transmitted anywhere. 
##   It is used to enable first-time help, when DEFAULT_GITHUB_URL is not set, for example

'USAGE_GITMYNOTES_TOTAL': 0
'USAGE_NOTES_PROCESSED': 0
'USAGE_FOLDERS_PROCESSED': 0


